version: '3.0'

services:
  usm-api:
    image: usm-api
    build:
      context: "."
    container_name: usm-api
    ports:
      - "8110:8110"
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_DB
      - MONGO_USER_FILES_BUCKET
      - MONGO_POST_FILES_BUCKET
    depends_on:
      - mongo
    volumes:
      - ".:/app"

  usm-test:
    image: usm-test
    container_name: usm-test
    build:
      context: "."
      dockerfile: Dockerfile-test
    depends_on:
      - mongo
    environment:
      - MONGO_HOST
      - MONGO_PORT

  mongo:
    image: mongo:5.0.17
    container_name: mongo-usm
    # ports:
    #   - "27017:27017"