appVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-router
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    # nginx.ingress.kubernetes.io/use-regex: 'true'
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  # ingressClassName: nginx
  rules:
    - http:
        paths:
          - host: "$NGINX_INGRESS_IP.nip.io"
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: api-cluster-ip-service
                port:
                  number: 8110